### ISSUE TITLE
generate opengraph tags to enable rich embeds

### ISSUE THREAD

**Issue by the6p4c** [delan/autost#21]
there are a few relevant standards:
- [twitter cards](https://developer.x.com/en/docs/twitter-for-websites/cards/overview/abouts-cards)
- [the open graph protocol](https://ogp.me/)

potentially, the metadata cohost embeds into live post pages could serve as a minimum viable set of information.

this may also open a can of worms where users are able to specify meta tags they want added to all/individual pages (e.g. `<meta name="twitter:site">`).

**Comment by delan** [comment]
done in [1.1.0](https://github.com/delan/autost/releases/tag/1.1.0) :)
