### ISSUE TITLE
Properly handle chosts with empty displayName

### ISSUE THREAD

**Issue by VinDuv** [delan/autost#23]
I never set a display name on [my cohost account](https://cohost.org/VinDuv), so when exported by `cohost2json`, my posts’ JSON have `postingProject.displayName` set to `""`.

This causes `cohost2autost` to generate posts with
```xml
<link rel="author" href="https://cohost.org/VinDuv" name=" (@VinDuv)">
<meta name="author_display_name" content="">
```

and the rendered posts show `(@VinDuv)` as author.

I think `cohost2autost` should set the author name to `@handle` if the displayName is blank (maybe `author_display_name` too? not sure), and `render` should show only the display handle without parentheses if the display name is blank or identical to the display handle.

**Comment by delan** [comment]
done in [5376d607a03cf...5138d370dd2ab](https://github.com/delan/autost/compare/5376d607a03cfd5c31fc4f812df9da0ea6988dcd...5138d370dd2abfc773201373842841eb4a64f812)! how does that look now?

**Comment by VinDuv** [comment]
Looks great, thanks!
